# Generated by Django 3.1.2 on 2020-11-03 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201102_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iamgen',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
