# Generated by Django 3.1.2 on 2020-11-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201102_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Github'),
        ),
    ]
